<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Script Template</name>
   <tag></tag>
   <elementGuidId>5c6367c3-d55f-4164-bb30-0ed5a44c3417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddScriptTemplate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAddScriptTemplate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a249fbe2-07c8-46aa-ba85-6da3571cb26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>aabf4375-efce-4524-b92e-b69d9c4b8998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>354d62a5-1cf4-4d4e-a975-c978136951a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddScriptTemplate</value>
      <webElementGuid>09be0953-e5d2-4b70-a32b-f6ed60b744cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Script Template</value>
      <webElementGuid>dd0d32d0-614c-4e83-bec9-91c17d36d862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddScriptTemplate&quot;)</value>
      <webElementGuid>bf1e7eca-61dc-4607-88bd-4aa49c6b3816</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAddScriptTemplate']</value>
      <webElementGuid>89b94236-6d9c-496e-8c29-9f5ae9636a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-Actions']/button</value>
      <webElementGuid>8af4199f-f0c0-499d-9756-ee6470ddbeae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Script Templates'])[2]/following::button[1]</value>
      <webElementGuid>ca976cc7-c73d-49d3-b80a-620cebc3d883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J1'])[1]/following::button[1]</value>
      <webElementGuid>78e443b8-e105-490c-8cf3-bd006e9d3f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search input'])[1]/preceding::button[1]</value>
      <webElementGuid>00f9a2f3-515d-46b6-8806-2ea383d05315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>217f6d63-eb74-4ddf-b191-4bfd01539c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnAddScriptTemplate' and (text() = 'Script Template' or . = 'Script Template')]</value>
      <webElementGuid>ff6aabf0-2c71-44ec-8f11-aefb62d36211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
