<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Script Template_1</name>
   <tag></tag>
   <elementGuidId>fd36387d-c43e-4748-9057-e899700964b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddScriptTemplate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAddScriptTemplate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>126bc31c-70a3-4813-b220-eb532f0e9c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>b5f8790f-edc2-4a55-892f-9964045a5d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0e94269-62e4-4fab-9a89-b3b97ecd5368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddScriptTemplate</value>
      <webElementGuid>a2ba7328-bed4-4d6f-a93f-bb638f20affb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Script Template</value>
      <webElementGuid>a0d1c209-6ce0-4ee1-ac3c-33615323517a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddScriptTemplate&quot;)</value>
      <webElementGuid>1af189e8-d598-4b34-92ad-f70553a70b80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAddScriptTemplate']</value>
      <webElementGuid>e941e2c8-d92c-45b2-9ccb-5c5e73264f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-Actions']/button</value>
      <webElementGuid>3d01b5a4-09ee-47fc-94a9-2f126d4c805f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Script Templates'])[2]/following::button[1]</value>
      <webElementGuid>3c1c878f-969e-4914-91a6-8b85eab3ca20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J1'])[1]/following::button[1]</value>
      <webElementGuid>31cad44f-953c-4cb9-8803-198b0bf8835d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search input'])[1]/preceding::button[1]</value>
      <webElementGuid>3d5dbaca-8d03-4441-9a22-82f906049314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>93dd2c99-723b-47f3-8c8d-7bc3fe2ab2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnAddScriptTemplate' and (text() = 'Script Template' or . = 'Script Template')]</value>
      <webElementGuid>60668692-f9a6-4aeb-bf38-6d113908e287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
