<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout</name>
   <tag></tag>
   <elementGuidId>0b14fcb6-f545-4098-b960-24f298793aeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b2-User_Popover']/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.vertical-align.flex-direction-row.full-width.column-gap-xs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>093330bc-5c11-49a8-969a-6e9743a20dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vertical-align flex-direction-row  full-width column-gap-xs</value>
      <webElementGuid>4089f2c2-ca91-49cc-acca-183a129395bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>8bbdd418-3fd6-4367-9a3d-f91493b24dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b2-User_Popover&quot;)/div[@class=&quot;popover popover-position-bottom popover-expanded&quot;]/div[@class=&quot;popover-bottom&quot;]/a[@class=&quot;auto-height auto-width&quot;]/div[@class=&quot;vertical-align flex-direction-row  full-width column-gap-xs&quot;]</value>
      <webElementGuid>7fdb4861-6bb7-4648-aeeb-c69e63eff126</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b2-User_Popover']/div/div[2]/a/div</value>
      <webElementGuid>7fd4e438-4743-441b-95f4-47ae19c20ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J1'])[1]/following::div[3]</value>
      <webElementGuid>9218fd08-c466-4e90-b67e-7861dd2df4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clientèle Perks Capture'])[1]/following::div[11]</value>
      <webElementGuid>d27bf252-9a0b-4034-a515-fd63794ad41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Script Templates'])[2]/preceding::div[4]</value>
      <webElementGuid>1d547477-db15-4eac-b060-4a5a5e3ab3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a/div</value>
      <webElementGuid>3c85f761-3bac-4b81-84d1-39dc944db23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>0ea04b84-990b-4fbe-ae80-eec9233fea37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
