<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_J1_b2-b2-Popover_Icon</name>
   <tag></tag>
   <elementGuidId>53465f9e-1874-4bbf-82fb-6c3a38f29c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b2-Popover_Icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b2-Popover_Icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cc30463-6935-4212-b972-f07caffa8e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-left-base padding-right-s</value>
      <webElementGuid>602e383b-2ef7-4c78-8a62-7ad694337e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b2-Popover_Icon</value>
      <webElementGuid>264d9a21-69b7-4bb6-ae26-437cb93b780f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b2-Popover_Icon&quot;)</value>
      <webElementGuid>893b193c-2f57-42f4-901f-8331f109733c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b2-Popover_Icon']</value>
      <webElementGuid>440f024a-7773-43d9-b8b0-3a86a403020b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b2-b5-Content']/div[2]</value>
      <webElementGuid>72c2ea97-8b07-476f-960d-dbfe3b8c5ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J1'])[1]/following::div[1]</value>
      <webElementGuid>7328b9dc-9d6d-4296-9993-bde012f83049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clientèle Perks Capture'])[1]/following::div[9]</value>
      <webElementGuid>31cdfa45-3ac7-49cd-b298-6f2f39811c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Script Templates'])[2]/preceding::div[2]</value>
      <webElementGuid>352f22cc-7654-4be3-abfe-1bf41c6c49ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Script Template'])[1]/preceding::div[3]</value>
      <webElementGuid>d3c28824-da17-4d4c-8b8c-643a2cad22bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div[2]</value>
      <webElementGuid>fe6d845c-e16c-4b8d-bc96-868bb1cad367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b2-Popover_Icon']</value>
      <webElementGuid>16f48f61-36bf-4a71-a11d-fb0fac290c7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
