<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Script TemplatesScript Template</name>
   <tag></tag>
   <elementGuidId>84f3e25e-2144-43aa-adc1-3e845e70334c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b1-SubHeader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-SubHeader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bdffbfcc-95da-41f8-8911-592f1a91cc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-header-content ThemeGrid_Container ph</value>
      <webElementGuid>7750a64f-d84c-4e90-a252-15af8f5b0899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-SubHeader</value>
      <webElementGuid>30d15c21-43da-4802-a48e-9fa57e84c00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Script TemplatesScript Template</value>
      <webElementGuid>cb3e0b3b-1779-498d-a08c-cf00b83775f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-SubHeader&quot;)</value>
      <webElementGuid>1b443af7-8482-42f9-9b6f-ebbda08ecff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b1-SubHeader']</value>
      <webElementGuid>eeccef05-9635-4e0d-ae92-9fbb887eacdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-LayoutWrapper']/div/div</value>
      <webElementGuid>36fe5e38-fc9d-4a95-8275-39827a16bd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[2]</value>
      <webElementGuid>96de1a64-8478-4496-a489-2ecea9e44027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J1'])[1]/following::div[7]</value>
      <webElementGuid>7a262de1-40be-4f9b-9c54-f6f104ed11fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>cf1b57d5-75d5-4834-be12-ca70e60f4e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b1-SubHeader' and (text() = 'Script TemplatesScript Template' or . = 'Script TemplatesScript Template')]</value>
      <webElementGuid>151e825f-f818-4528-b494-d5dd51f42da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
