<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Template_Name</name>
   <tag></tag>
   <elementGuidId>c9bb3d6d-b98f-450e-b9d7-f962a044649c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l3_0-2_0-b8-Content']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l3_0-2_0-b8-Content > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1Life_Terms&amp;Conditions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f32cb68-a2fe-4dd0-bd14-278b1303480f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Life_Terms&amp;Conditions</value>
      <webElementGuid>be5c9197-d832-406c-b3fe-3e8fe0bffb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l3_0-2_0-b8-Content&quot;)/span[1]</value>
      <webElementGuid>918f571c-7e9a-4864-a439-52b6646b3df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l3_0-2_0-b8-Content']/span</value>
      <webElementGuid>6385cba5-73b1-4758-bda4-67f05ce2d38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Stamp'])[1]/following::span[2]</value>
      <webElementGuid>8882654a-2b3b-47d0-a6a4-c82c26ec1aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stamped By'])[1]/following::span[2]</value>
      <webElementGuid>2dfb25d5-5483-4742-9fbc-d2af78236cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[2]/preceding::span[2]</value>
      <webElementGuid>6195e467-b1db-46e0-a60b-602462ca0bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JvS 11'])[2]/preceding::span[3]</value>
      <webElementGuid>d83f2429-bc9c-44e5-87aa-a93922bb799f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1Life_Terms&amp;Conditions']/parent::*</value>
      <webElementGuid>ffb8c8cf-235b-471c-b83d-ba87f7d46761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/div/span</value>
      <webElementGuid>f3a0f0a7-0b7c-4f72-8a7d-c6ed82f4fb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1Life_Terms&amp;Conditions' or . = '1Life_Terms&amp;Conditions')]</value>
      <webElementGuid>1b5f42a9-76f3-4ce4-85a4-bd80465c3957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
