<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BoldKeyboard shortcut CtrlB</name>
   <tag></tag>
   <elementGuidId>21eea090-0270-4893-a3e0-fa9e7f777862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cke_30']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cke_30</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@id = 'cke_30' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Bold&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Bold (Ctrl+B)' and (text() = ' Bold Keyboard shortcut Ctrl+B' or . = ' Bold Keyboard shortcut Ctrl+B')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25c566f1-e4d7-4b46-85e5-5adbe403149f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_30</value>
      <webElementGuid>bd989938-914d-4b77-908d-92eebc8abf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_button cke_button__bold cke_button_off</value>
      <webElementGuid>425dafe9-594d-4a11-a1e8-345655f653cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void('Bold')</value>
      <webElementGuid>e11c3dec-6d89-4d52-ab23-ec7994042ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bold (Ctrl+B)</value>
      <webElementGuid>ea1edd94-7af2-4730-a40e-47fa7e028f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c99245ee-8bb5-4b82-9c2a-483e1601aef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9ca0a0b3-b66e-45c4-af20-3935b48d94bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30a6f639-a8be-40c0-aaf0-0ff074f94355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_30_label</value>
      <webElementGuid>7ad19ed3-988a-45b6-bb75-bdb5035c8c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cke_30_description</value>
      <webElementGuid>8f761494-abfa-46fa-a42b-90062498c864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9774ae3b-e716-4f13-9556-12389e64abb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4430fe5b-649b-4ca5-afc5-a8f62bc20dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47f6a4da-a234-456e-be09-96011cb259ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(28,event);</value>
      <webElementGuid>11c3407e-a59b-4ae8-8672-34303a18f3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>return CKEDITOR.tools.callFunction(29,event);</value>
      <webElementGuid>8f177231-f578-47de-b701-67799e6822eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>CKEDITOR.tools.callFunction(30,this);return false;</value>
      <webElementGuid>c8637099-c2db-4bbe-a589-96d48a3ac9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Bold Keyboard shortcut Ctrl+B</value>
      <webElementGuid>43b33268-8a68-4a51-8115-2edf9f198582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_30&quot;)</value>
      <webElementGuid>5357c404-7b97-4be3-a2ff-51d483118266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cke_30']</value>
      <webElementGuid>9757b458-9d14-4cb0-bd8a-60001f584caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cke_29']/span[3]/a</value>
      <webElementGuid>16d6afb6-b70b-4cd2-8a01-cb99685e8b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Styles'])[1]/following::a[1]</value>
      <webElementGuid>58ca691d-5021-490f-b83b-f4e9ddbf73a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replace'])[1]/following::a[1]</value>
      <webElementGuid>a6507a07-bed8-4ae1-ae2c-6370f7531d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:void('Bold')&quot;)]</value>
      <webElementGuid>55f939a0-3081-43fa-94e9-7d4fe499464d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/span[3]/a</value>
      <webElementGuid>90170bdb-df59-4b4d-9721-82774dd13879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cke_30' and @href = concat(&quot;javascript:void(&quot; , &quot;'&quot; , &quot;Bold&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Bold (Ctrl+B)' and (text() = ' Bold Keyboard shortcut Ctrl+B' or . = ' Bold Keyboard shortcut Ctrl+B')]</value>
      <webElementGuid>aced64b3-09a4-4e8b-ba72-989e46435ec9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
