<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Raw json</name>
   <tag></tag>
   <elementGuidId>f4020584-c82c-401c-8d2a-1f5a8b620799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b18-btnBeautifyJson']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b18-btnBeautifyJson</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Raw json&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>031a4b6e-31d4-47d1-9cdb-6f232ae4f6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-small border-size-none margin-left-s</value>
      <webElementGuid>45c6b93a-23ab-49c0-bba7-a5e3d8be3071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6d5c2bf-2c81-497a-8cd7-f79896e431cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b18-btnBeautifyJson</value>
      <webElementGuid>8ff81e91-c83e-4a36-8afd-914ef9e0d07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Raw json</value>
      <webElementGuid>47296812-a37e-478f-bff6-42e191e8ccd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b18-btnBeautifyJson&quot;)</value>
      <webElementGuid>c93e1a55-85b4-4075-8394-45e0cffe76c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b18-btnBeautifyJson']</value>
      <webElementGuid>3a0d975a-95b8-474f-b883-79f71ec83b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b18-b17-Title']/div/div[2]/button</value>
      <webElementGuid>a7b06752-a14f-4c2d-9172-64bda858acfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Json is Valid'])[1]/following::button[1]</value>
      <webElementGuid>0fa89074-cb4c-47de-b307-d62c0d1b724f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/following::button[1]</value>
      <webElementGuid>417541cd-ee4f-470a-a1b6-9d7e428fe18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Run'])[2]/preceding::button[1]</value>
      <webElementGuid>39d44d50-dd49-472f-85a8-2955fe714eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>260ab407-11d5-4a71-9a70-ac78a11e7fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b18-btnBeautifyJson' and (text() = 'Raw json' or . = 'Raw json')]</value>
      <webElementGuid>446673e2-3da0-4fab-9230-2543a85e2c99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
