<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Merge Fields</name>
   <tag></tag>
   <elementGuidId>4d2842cb-4963-4609-aa94-6780c006c4f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='0.grp8po4g0yn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;0.grp8po4g0yn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Merge Fields&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29f9abe9-7a6a-48f8-81ee-fb7ae9a848e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-tabs__header-item</value>
      <webElementGuid>7ef1e891-16d0-416c-936d-e0ebb823586b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0.grp8po4g0yn</value>
      <webElementGuid>b3737248-ff69-424c-8161-5b6a9f4d9cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>447bc0c2-737b-4f2f-987c-28695d7a3a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>61e53cce-91fb-43cf-b403-aad731edabae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>97c8ba73-7b1d-42fa-91cf-2346478cb880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e95471ba-0db5-4157-be1e-f8dc82d05726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b18-$b12</value>
      <webElementGuid>17a4f26b-cbc3-4c3a-8508-ebc22f18ee69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Merge Fields</value>
      <webElementGuid>57a260f9-6a0c-4fd1-b7c1-99ec70d6abdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b18-$b10&quot;)/button[@class=&quot;osui-tabs__header-item&quot;]</value>
      <webElementGuid>b066a8ce-5d6b-4e56-b56d-a31e4f57ace3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='0.grp8po4g0yn']</value>
      <webElementGuid>bddfbc93-3d13-4da5-acc1-b90bcbc510ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b18-$b10']/button</value>
      <webElementGuid>4f03aa5e-15d5-4816-80b0-0cf303280f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auntie Smith'])[3]/following::button[1]</value>
      <webElementGuid>7aacf48c-8ef2-47b7-b8d1-56718d52fb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='janith@email.com'])[1]/following::button[1]</value>
      <webElementGuid>1aae6a87-331e-43b0-93f9-f854f88c5f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Json'])[2]/preceding::button[1]</value>
      <webElementGuid>ab41e662-9597-4a33-9f3e-07f549ec6506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/button</value>
      <webElementGuid>afa9d011-9bb5-4388-8afd-9f055cb47d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = '0.grp8po4g0yn' and (text() = 'Merge Fields' or . = 'Merge Fields')]</value>
      <webElementGuid>afac1990-1c00-409a-bb94-7220235e49c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
