<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Generate Merge Fields</name>
   <tag></tag>
   <elementGuidId>4b011084-f779-4efd-8d8f-a7ca2cc6ec0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b10-Button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b10-Button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0f63e3f-6261-4e1a-9cc6-83e6c1fbfae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-btn-loading OSInline</value>
      <webElementGuid>18d83aec-5cb2-49cc-a84a-897555c5f26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0.xifedabshl</value>
      <webElementGuid>aa5ab387-6f7e-48a1-9e26-e8895d05f130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b10-Button</value>
      <webElementGuid>f7032994-cff2-4e7c-9e86-525ec6dce092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>5a432e68-f105-4a25-ad98-97996e69a2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>79db5dfa-8801-4464-8378-66304a5f7057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generate  Merge Fields</value>
      <webElementGuid>28b079e7-18ce-49f2-922e-417f54e0829f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b10-Button&quot;)</value>
      <webElementGuid>7e87f45b-09ea-4c0b-a129-b548dec10015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b10-Button']</value>
      <webElementGuid>19ea6a19-b957-4742-ac05-d3819c568e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b10']/div</value>
      <webElementGuid>b58b5ff9-0ea5-46ed-a59b-d09868c9c3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge Fields'])[1]/following::div[4]</value>
      <webElementGuid>8ef5114a-90c4-4026-964c-b89eee69e22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge Fields Parenthesis'])[1]/following::div[12]</value>
      <webElementGuid>d0a3b1d7-1cf8-454d-b9a8-dc85a5401adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/preceding::div[3]</value>
      <webElementGuid>9230708f-c7b0-4cf9-9fb0-53c9f4b23ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>adca6ce3-fd6c-4db8-8a15-ca83ec9acec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = '0.xifedabshl' and @id = 'b10-Button' and (text() = 'Generate  Merge Fields' or . = 'Generate  Merge Fields')]</value>
      <webElementGuid>f466becd-bc3f-4328-80ec-5cf53c749dc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
