<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Copy</name>
   <tag></tag>
   <elementGuidId>6b249aee-4a71-4420-ba76-da1b21c26f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b11-Button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b11-Button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d8d816c2-839a-4af5-8e1b-47f1f93d5284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-btn-loading OSInline margin-left-s</value>
      <webElementGuid>8ad59647-74b1-4405-a8d2-e7142e0fc0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0.ttxb311uh1r</value>
      <webElementGuid>5a58f650-620f-4cfb-bd7e-9f743ec04fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b11-Button</value>
      <webElementGuid>f752b332-c1ef-4862-bdee-45b9278d87b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>d20b3611-ea81-405b-aeb4-974f70aa62f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dcd3ba1f-b66d-4292-ae9d-93e98ff0bb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy</value>
      <webElementGuid>683a750c-20d5-438b-99fe-c6423f37aa44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b11-Button&quot;)</value>
      <webElementGuid>d195edd1-d163-4667-be35-54cb3fa7ac7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b11-Button']</value>
      <webElementGuid>09f53607-4c2e-43b4-8d25-304fe6625bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b11']/div</value>
      <webElementGuid>fe94164c-a194-48ae-acaa-03022a43fe2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate  Merge Fields'])[1]/following::div[2]</value>
      <webElementGuid>bb3c011c-3c2a-4f02-a160-6e9494e565d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge Fields'])[1]/following::div[7]</value>
      <webElementGuid>286f1a21-d30c-45c9-a8ad-3034cb39b03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>0688bcc9-3cb1-4b3f-b963-714ca7f10d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = '0.ttxb311uh1r' and @id = 'b11-Button' and (text() = 'Copy' or . = 'Copy')]</value>
      <webElementGuid>8c0a3439-b3d2-42fb-b222-e586191f8c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
