<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MergeFields_Parenthesis_TemplateDetail_VariableSuffix_Input</name>
   <tag></tag>
   <elementGuidId>fb226572-013a-46fd-b5ad-adabff209542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TemplateDetail_VariableSuffix_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TemplateDetail_VariableSuffix_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>268eed97-9a23-4bb9-b9c3-9ab1b97a03b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>75d60464-641c-49ae-ac5b-b65cc666d625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c6f5aa9-af42-4690-bd65-bcdf434eb66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter suffix e.g. }}</value>
      <webElementGuid>094412b4-c6d4-4d05-aa1a-5c8f0496f33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2501337f-adf4-4f34-802b-7dcc86d4223b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TemplateDetail_VariableSuffix_Input</value>
      <webElementGuid>e2867c62-137c-4947-b812-063260d22a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TemplateDetail_VariableSuffix_Input&quot;)</value>
      <webElementGuid>75254313-ed14-47aa-abf8-7e9840e00ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TemplateDetail_VariableSuffix_Input']</value>
      <webElementGuid>a8cb8c08-a4ab-4454-b1b4-9f615a549f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-Column2']/span/input</value>
      <webElementGuid>e2cf42dc-ffaa-4a25-82fd-a0fddc25f653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span/input</value>
      <webElementGuid>59836829-e92e-4d20-aa06-ef5f9d3cdc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter suffix e.g. }}' and @id = 'TemplateDetail_VariableSuffix_Input']</value>
      <webElementGuid>5733d304-b71d-4883-ae89-2851f0cee788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
