<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MergeFields_Parenthesis_TemplateDetail_VariablePrefix_Input</name>
   <tag></tag>
   <elementGuidId>391e54c7-81f9-4dae-b563-dd8b5c8c2e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TemplateDetail_VariablePrefix_Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TemplateDetail_VariablePrefix_Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b0a1dfa-9592-4ece-bfd2-11f2bd79ab18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>b671c7e9-6609-41e5-b317-816214ca65bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11f406e6-f98a-4cbe-ad8a-0e6e8e77e843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter prefix e.g. {{</value>
      <webElementGuid>efad1080-3711-455c-a654-6abcc9cf31b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>47d56626-2bec-4eb5-a9c0-a0d4d6665e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TemplateDetail_VariablePrefix_Input</value>
      <webElementGuid>1bc19122-5d29-4034-a6fa-add0cdd96494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TemplateDetail_VariablePrefix_Input&quot;)</value>
      <webElementGuid>f3e7be39-b148-4c34-94b5-f15b57e5f104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TemplateDetail_VariablePrefix_Input']</value>
      <webElementGuid>7a4317c6-7bb5-435c-8eb5-f1cea196ec00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-Column1']/span/input</value>
      <webElementGuid>c54ee542-170d-49c6-aae2-ad743a221542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span/input</value>
      <webElementGuid>c2eed62a-a79e-40ee-afcc-428bc0c808ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter prefix e.g. {{' and @id = 'TemplateDetail_VariablePrefix_Input']</value>
      <webElementGuid>1b21960c-d58e-4442-9eb7-049f4f18022d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
