<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Template_Type</name>
   <tag></tag>
   <elementGuidId>9bca8c92-f59b-403d-92ad-579795587e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdown_ScriptTemplateTypes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdown_ScriptTemplateTypes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2c2900fc-ed12-4b3c-b6af-7f8fcb535a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>21741992-a39b-4a3b-af6e-adc8a7b146f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc1a8604-f27b-4151-9c3e-feafae6fcd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdown_ScriptTemplateTypes</value>
      <webElementGuid>b93ae47a-cef7-4f05-af76-ab923ac16d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Template TypeEmailJsonPrivacy PolicyPush NotificationTerms And ConditionsText MessageUnknown</value>
      <webElementGuid>ff7b17b6-8c0b-41a7-922d-fbf22f7667a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown_ScriptTemplateTypes&quot;)</value>
      <webElementGuid>8f1b045a-7146-4826-a009-4cd0476eb07f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdown_ScriptTemplateTypes']</value>
      <webElementGuid>3dfc86f5-d68a-4c9c-ba36-ba09d588c1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown_ScriptTemplateTypes-container']/select</value>
      <webElementGuid>6243870e-f634-443c-b6b4-770990adc922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[1]</value>
      <webElementGuid>f0bd3dd6-febb-4284-b865-2e7d6d3067b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::select[1]</value>
      <webElementGuid>9e964f0b-888c-4c20-8a2b-1336d2d55a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Module'])[1]/preceding::select[1]</value>
      <webElementGuid>3cabbe02-3d9c-47e9-995a-4be28417980b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[2]</value>
      <webElementGuid>be842f73-058f-472a-928e-a8458691aae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1a360f46-5a44-4953-9358-c064675f6b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdown_ScriptTemplateTypes' and (text() = 'Select Template TypeEmailJsonPrivacy PolicyPush NotificationTerms And ConditionsText MessageUnknown' or . = 'Select Template TypeEmailJsonPrivacy PolicyPush NotificationTerms And ConditionsText MessageUnknown')]</value>
      <webElementGuid>c15e4d82-e062-42a7-8b6c-e4de071850c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
