<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Application_Module</name>
   <tag></tag>
   <elementGuidId>2b20ce6b-2a50-46f3-951e-081a5c7c1691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdown_ApplicationModules']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropdown_ApplicationModules</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>851ae56b-25d9-4855-a901-42f88ef4edfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>5ba921e0-647c-4e83-b254-d70bb9431873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>578192da-2c21-4dd1-b7bf-5aaad9c3c1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdown_ApplicationModules</value>
      <webElementGuid>ef689cbc-5289-4d96-a73e-609b26384352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Application Module1Life (OneLifeRewardsApp)Android back button (Android_back_button)Android Intent Handler (AndroidIntentHandler_Plugin)App BuildInfo Plugin (AppBuildInfoPlugin)App Feedback (ECT_Provider)App Version Plugin (AppVersionPlugin)AppLauncherPlugin (AppLauncherPlugin)Audio Record Plugin (AudioRecordPlugin)B3 Funeral (BTFuneralApp)B3 Funeral Policy Option (B3PolicyOption)BinaryData Client Side (BinaryData_ClientSide_CW)BPT Governor (BPTGovernor)Broker Online (BrokerOnline)Broker Online Clone (BrokerOnlineClone)Calendar Plugin (CalendarPlugin)Call Me Back Clientèle (CallMeCLI)Card IO Plugin (CardIOPlugin)CBC Chat Demo (CBCChatDemo)CBC Connect (CBCConnect)Clientele (Clientele)Clientèle Admin (ClienteleAdminPortal)Clientèle Clone (ClienteleClone04)Clientèle Connect (ClienteleConnectWebPOC)Clientèle Online (ClienteleOnline)Clientèle Online Sales (ClienteleOnlineSales)Clientèle Perks Capture (ClientelePerksCapture)Clientèle Self Service (ClienteleSelfService)ClientèleNew (ClienteleNew)Common Plugin (CommonPlugin)Contacts Plugin (ContactsPlugin)Copy to Clipboard Reactive (Clipboard_CW)DB Cleaner on Steroids (DBCleanerOnSteroids)DBCleaner (DBCleaner)DebiCheck Assist (DebiCheck)DebiCheck Tap (DebiCheckTapDemo)DebtBusters (DebtBusters)Dynamic Forms (DynamicForms)EAT App (EATApp)Embedded Process Automation (EPA_Taskbox)Energy Portal (EnergyPortal)Facebook Pixel (FacebookPixel)Factory Configuration (FactoryConfiguration)File Plugin (FilePlugin)File Viewer Plugin (FileViewerPlugin)Firebase CM Compat R&amp;D (FirebaseCloudMessagingPlugin)Firebase Mobile Sample (FirebaseMobileSample)Hollard Lesotho (HollardLesotho)Home Insurance BO (HomeInsurance_BackOffice)Home Insurance Portal (HomeInsurancePortal)HTML Display Component for React Web and Mobile (HTMLComponent)Html2PdfConverter (HtmlToPdfConverter)IFA (IFA)IFA Clone (IFAClone01)IFA Online (IFAOnline)IFA Online Clone (IFAOnlineClone)InAppBrowser Plugin (InAppBrowserPlugin)Inspire (Inspire)Inspire Admin (InspireAdmin)Inspire FM (Inspire250410_FM)Inspire_OLD (Inspire_OLD)InspireReactive (InspireReactive)JustMoney MyMoney Saver (JustMoney)Key Store Plugin (KeyStorePlugin)Local Notifications Plugin (LocalNotificationsPlugin)Local Storage JS (LocalStorage)Location Plugin (LocationPlugin)Lottie Animations (LottieAnimations)LSF (Shembe)LSF Web (LSFHome)Lumkani (LumkaniRewards)Mobile Utilities (MobileUtilities)My Rewards Club (MyRewardsClubApp)NFC Plugin -Demo (NFCSample)Office Space Manager (OfficeSpaceManagerLog_Lib)Old Apps (PFSApp_202208211901)OneSignal Plugin (OneSignalPlugin)Online Sales Clone (ClienteleOnlineClone1124)OutSystems Meetups Survey (OutSystemsMeetupBackOffice)OutSystems Meetups Survey -Demo (OutSystemsMeetupSurvey)OutSystems UI Mobile Style Guide Template (Template_MobileStyleGuide)OutSystems UI Style Guide Preview (StyleGuidePreview)OutTracker (OutTracker)PDF Viewer Reactive (PDFViewerReactive)PFS (PFSApp)PFS Clone (PFSAppClone)PFS Policy Option (PFSOption)Phone Template 01 (PhoneTemplate01)Phone Template 02 (PhoneTemplate02)Phone Template 03 (PhoneTemplate03)Phone Template 11 (PhoneTemplate11)PhoneCall (PhoneCall)QR Code Lead (QRCodeLead)Reactive Signature Test (ReactiveSignatureTest202104)Reactive Template 01 (ReactiveTemplate01)REST HTTP Codes (Wiki_UI)Rewards Claims (RewardsClaims)Silk UI Web (WebPatterns)Social Sharing Plugin (SocialSharingPlugin)Speech Recognition Plugin (SpeechRecognitionPlugin)Tablet Template (TabletTemplate01)Tablet Template 11 (TabletTemplate11)Time Zone (TimeZone)Time Zone Service -Demo (TimeZoneDemo)TimezoneReactiveUtils (TimezoneReactiveUtils)Touch ID Plugin (TouchIdPlugin)TouchId 1812171440 (TouchId1812271440)Trigger Action (TriggerAction)Users (Users)WinWheel (WinWheel)Z120921 (Z120921)</value>
      <webElementGuid>282c6ae1-9386-446a-8428-2660cf7b86bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown_ApplicationModules&quot;)</value>
      <webElementGuid>6c19074d-2c6f-4003-9cc6-e7c384369175</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdown_ApplicationModules']</value>
      <webElementGuid>0ee70200-e961-4381-bdf0-0591418260e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown_ApplicationModules-container']/select</value>
      <webElementGuid>f0f4119b-c308-4c6c-991b-6de7e3f429a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Module'])[1]/following::select[1]</value>
      <webElementGuid>0fbc6bc4-8777-40e4-b43b-62250a2f0cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[2]</value>
      <webElementGuid>e7b5d285-1dd6-4a32-8140-4f34217c7540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[1]</value>
      <webElementGuid>dab534df-a970-4da1-8087-c932ca2ce145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merge Fields Parenthesis'])[1]/preceding::select[1]</value>
      <webElementGuid>a6a9b603-f654-49d6-850e-faa1aeac1298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>5b6ee396-58a2-4178-bbde-a1561a2e6448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdown_ApplicationModules' and (text() = 'Select Application Module1Life (OneLifeRewardsApp)Android back button (Android_back_button)Android Intent Handler (AndroidIntentHandler_Plugin)App BuildInfo Plugin (AppBuildInfoPlugin)App Feedback (ECT_Provider)App Version Plugin (AppVersionPlugin)AppLauncherPlugin (AppLauncherPlugin)Audio Record Plugin (AudioRecordPlugin)B3 Funeral (BTFuneralApp)B3 Funeral Policy Option (B3PolicyOption)BinaryData Client Side (BinaryData_ClientSide_CW)BPT Governor (BPTGovernor)Broker Online (BrokerOnline)Broker Online Clone (BrokerOnlineClone)Calendar Plugin (CalendarPlugin)Call Me Back Clientèle (CallMeCLI)Card IO Plugin (CardIOPlugin)CBC Chat Demo (CBCChatDemo)CBC Connect (CBCConnect)Clientele (Clientele)Clientèle Admin (ClienteleAdminPortal)Clientèle Clone (ClienteleClone04)Clientèle Connect (ClienteleConnectWebPOC)Clientèle Online (ClienteleOnline)Clientèle Online Sales (ClienteleOnlineSales)Clientèle Perks Capture (ClientelePerksCapture)Clientèle Self Service (ClienteleSelfService)ClientèleNew (ClienteleNew)Common Plugin (CommonPlugin)Contacts Plugin (ContactsPlugin)Copy to Clipboard Reactive (Clipboard_CW)DB Cleaner on Steroids (DBCleanerOnSteroids)DBCleaner (DBCleaner)DebiCheck Assist (DebiCheck)DebiCheck Tap (DebiCheckTapDemo)DebtBusters (DebtBusters)Dynamic Forms (DynamicForms)EAT App (EATApp)Embedded Process Automation (EPA_Taskbox)Energy Portal (EnergyPortal)Facebook Pixel (FacebookPixel)Factory Configuration (FactoryConfiguration)File Plugin (FilePlugin)File Viewer Plugin (FileViewerPlugin)Firebase CM Compat R&amp;D (FirebaseCloudMessagingPlugin)Firebase Mobile Sample (FirebaseMobileSample)Hollard Lesotho (HollardLesotho)Home Insurance BO (HomeInsurance_BackOffice)Home Insurance Portal (HomeInsurancePortal)HTML Display Component for React Web and Mobile (HTMLComponent)Html2PdfConverter (HtmlToPdfConverter)IFA (IFA)IFA Clone (IFAClone01)IFA Online (IFAOnline)IFA Online Clone (IFAOnlineClone)InAppBrowser Plugin (InAppBrowserPlugin)Inspire (Inspire)Inspire Admin (InspireAdmin)Inspire FM (Inspire250410_FM)Inspire_OLD (Inspire_OLD)InspireReactive (InspireReactive)JustMoney MyMoney Saver (JustMoney)Key Store Plugin (KeyStorePlugin)Local Notifications Plugin (LocalNotificationsPlugin)Local Storage JS (LocalStorage)Location Plugin (LocationPlugin)Lottie Animations (LottieAnimations)LSF (Shembe)LSF Web (LSFHome)Lumkani (LumkaniRewards)Mobile Utilities (MobileUtilities)My Rewards Club (MyRewardsClubApp)NFC Plugin -Demo (NFCSample)Office Space Manager (OfficeSpaceManagerLog_Lib)Old Apps (PFSApp_202208211901)OneSignal Plugin (OneSignalPlugin)Online Sales Clone (ClienteleOnlineClone1124)OutSystems Meetups Survey (OutSystemsMeetupBackOffice)OutSystems Meetups Survey -Demo (OutSystemsMeetupSurvey)OutSystems UI Mobile Style Guide Template (Template_MobileStyleGuide)OutSystems UI Style Guide Preview (StyleGuidePreview)OutTracker (OutTracker)PDF Viewer Reactive (PDFViewerReactive)PFS (PFSApp)PFS Clone (PFSAppClone)PFS Policy Option (PFSOption)Phone Template 01 (PhoneTemplate01)Phone Template 02 (PhoneTemplate02)Phone Template 03 (PhoneTemplate03)Phone Template 11 (PhoneTemplate11)PhoneCall (PhoneCall)QR Code Lead (QRCodeLead)Reactive Signature Test (ReactiveSignatureTest202104)Reactive Template 01 (ReactiveTemplate01)REST HTTP Codes (Wiki_UI)Rewards Claims (RewardsClaims)Silk UI Web (WebPatterns)Social Sharing Plugin (SocialSharingPlugin)Speech Recognition Plugin (SpeechRecognitionPlugin)Tablet Template (TabletTemplate01)Tablet Template 11 (TabletTemplate11)Time Zone (TimeZone)Time Zone Service -Demo (TimeZoneDemo)TimezoneReactiveUtils (TimezoneReactiveUtils)Touch ID Plugin (TouchIdPlugin)TouchId 1812171440 (TouchId1812271440)Trigger Action (TriggerAction)Users (Users)WinWheel (WinWheel)Z120921 (Z120921)' or . = 'Select Application Module1Life (OneLifeRewardsApp)Android back button (Android_back_button)Android Intent Handler (AndroidIntentHandler_Plugin)App BuildInfo Plugin (AppBuildInfoPlugin)App Feedback (ECT_Provider)App Version Plugin (AppVersionPlugin)AppLauncherPlugin (AppLauncherPlugin)Audio Record Plugin (AudioRecordPlugin)B3 Funeral (BTFuneralApp)B3 Funeral Policy Option (B3PolicyOption)BinaryData Client Side (BinaryData_ClientSide_CW)BPT Governor (BPTGovernor)Broker Online (BrokerOnline)Broker Online Clone (BrokerOnlineClone)Calendar Plugin (CalendarPlugin)Call Me Back Clientèle (CallMeCLI)Card IO Plugin (CardIOPlugin)CBC Chat Demo (CBCChatDemo)CBC Connect (CBCConnect)Clientele (Clientele)Clientèle Admin (ClienteleAdminPortal)Clientèle Clone (ClienteleClone04)Clientèle Connect (ClienteleConnectWebPOC)Clientèle Online (ClienteleOnline)Clientèle Online Sales (ClienteleOnlineSales)Clientèle Perks Capture (ClientelePerksCapture)Clientèle Self Service (ClienteleSelfService)ClientèleNew (ClienteleNew)Common Plugin (CommonPlugin)Contacts Plugin (ContactsPlugin)Copy to Clipboard Reactive (Clipboard_CW)DB Cleaner on Steroids (DBCleanerOnSteroids)DBCleaner (DBCleaner)DebiCheck Assist (DebiCheck)DebiCheck Tap (DebiCheckTapDemo)DebtBusters (DebtBusters)Dynamic Forms (DynamicForms)EAT App (EATApp)Embedded Process Automation (EPA_Taskbox)Energy Portal (EnergyPortal)Facebook Pixel (FacebookPixel)Factory Configuration (FactoryConfiguration)File Plugin (FilePlugin)File Viewer Plugin (FileViewerPlugin)Firebase CM Compat R&amp;D (FirebaseCloudMessagingPlugin)Firebase Mobile Sample (FirebaseMobileSample)Hollard Lesotho (HollardLesotho)Home Insurance BO (HomeInsurance_BackOffice)Home Insurance Portal (HomeInsurancePortal)HTML Display Component for React Web and Mobile (HTMLComponent)Html2PdfConverter (HtmlToPdfConverter)IFA (IFA)IFA Clone (IFAClone01)IFA Online (IFAOnline)IFA Online Clone (IFAOnlineClone)InAppBrowser Plugin (InAppBrowserPlugin)Inspire (Inspire)Inspire Admin (InspireAdmin)Inspire FM (Inspire250410_FM)Inspire_OLD (Inspire_OLD)InspireReactive (InspireReactive)JustMoney MyMoney Saver (JustMoney)Key Store Plugin (KeyStorePlugin)Local Notifications Plugin (LocalNotificationsPlugin)Local Storage JS (LocalStorage)Location Plugin (LocationPlugin)Lottie Animations (LottieAnimations)LSF (Shembe)LSF Web (LSFHome)Lumkani (LumkaniRewards)Mobile Utilities (MobileUtilities)My Rewards Club (MyRewardsClubApp)NFC Plugin -Demo (NFCSample)Office Space Manager (OfficeSpaceManagerLog_Lib)Old Apps (PFSApp_202208211901)OneSignal Plugin (OneSignalPlugin)Online Sales Clone (ClienteleOnlineClone1124)OutSystems Meetups Survey (OutSystemsMeetupBackOffice)OutSystems Meetups Survey -Demo (OutSystemsMeetupSurvey)OutSystems UI Mobile Style Guide Template (Template_MobileStyleGuide)OutSystems UI Style Guide Preview (StyleGuidePreview)OutTracker (OutTracker)PDF Viewer Reactive (PDFViewerReactive)PFS (PFSApp)PFS Clone (PFSAppClone)PFS Policy Option (PFSOption)Phone Template 01 (PhoneTemplate01)Phone Template 02 (PhoneTemplate02)Phone Template 03 (PhoneTemplate03)Phone Template 11 (PhoneTemplate11)PhoneCall (PhoneCall)QR Code Lead (QRCodeLead)Reactive Signature Test (ReactiveSignatureTest202104)Reactive Template 01 (ReactiveTemplate01)REST HTTP Codes (Wiki_UI)Rewards Claims (RewardsClaims)Silk UI Web (WebPatterns)Social Sharing Plugin (SocialSharingPlugin)Speech Recognition Plugin (SpeechRecognitionPlugin)Tablet Template (TabletTemplate01)Tablet Template 11 (TabletTemplate11)Time Zone (TimeZone)Time Zone Service -Demo (TimeZoneDemo)TimezoneReactiveUtils (TimezoneReactiveUtils)Touch ID Plugin (TouchIdPlugin)TouchId 1812171440 (TouchId1812271440)Trigger Action (TriggerAction)Users (Users)WinWheel (WinWheel)Z120921 (Z120921)')]</value>
      <webElementGuid>9d50cddd-767e-4b57-95b7-59b613896dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
