<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Json_Testing_Template_4</name>
   <tag></tag>
   <elementGuidId>55bbd612-ebca-4294-8735-b0b63e9e3ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l3_0-44_0-b8-Content']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l3_0-44_0-b8-Content > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d927d13b-c6de-4745-9004-d1ae5009c37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Json_Testing_Template_4</value>
      <webElementGuid>738965d8-6af7-41ce-95e3-90427b0e4d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l3_0-44_0-b8-Content&quot;)/span[1]</value>
      <webElementGuid>d931435f-8026-4787-be28-ceefdad668b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l3_0-44_0-b8-Content']/span</value>
      <webElementGuid>7ff8f6c9-b90a-4bc5-9cc7-d771aa6e5108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Stamp'])[1]/following::span[2]</value>
      <webElementGuid>de9a1f94-7f95-45d5-a649-fc7d3095e3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stamped By'])[1]/following::span[2]</value>
      <webElementGuid>63300915-4668-40dd-a2b0-bfb200263f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DebiCheck Assist (DebiCheck)'])[2]/preceding::span[1]</value>
      <webElementGuid>ec75056c-0446-4811-b294-8e738672daea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Json'])[2]/preceding::span[2]</value>
      <webElementGuid>c10e22b2-f098-41e1-901f-ee7039f95c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Json_Testing_Template_4']/parent::*</value>
      <webElementGuid>9229c2e8-2d97-4b22-83ef-06ec6d42fd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/div/span</value>
      <webElementGuid>a2267fb1-946a-4096-b0a1-8ce580f6066c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Json_Testing_Template_4' or . = 'Json_Testing_Template_4')]</value>
      <webElementGuid>bf60e8b3-4bfb-4c24-93f7-345157784042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
