<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_TemplateDetail_aa8ae6</name>
   <tag></tag>
   <elementGuidId>10c08b99-8743-4137-b790-6d3c17e4ed8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='TemplateDetail_TextArea_Description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TemplateDetail_TextArea_Description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dd1da9ae-4b6d-423c-95a4-3cc90b77b371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>0e7ccc11-5d2a-41fb-bc42-a6dd6746509b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8c53590b-1bb3-433d-8d3c-08ccbbe37dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the Description</value>
      <webElementGuid>46c35d0f-6dfd-492d-bfae-6b38ad7de12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>cc846a8b-3079-4acd-98a8-c1e4c3b6bc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TemplateDetail_TextArea_Description</value>
      <webElementGuid>2419fba0-275a-4f15-8774-b4a209b01fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TemplateDetail_TextArea_Description&quot;)</value>
      <webElementGuid>e49dbfab-b38b-4a18-8b14-5de51b6a31e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='TemplateDetail_TextArea_Description']</value>
      <webElementGuid>64e8ba0d-2a23-476c-a948-1d48255272c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TemplateDetail_Description']/span/textarea</value>
      <webElementGuid>cb20d749-2856-44e5-8e31-96d235821159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>fcb540bd-c47a-4bb7-8d02-36d8e4108b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter the Description' and @id = 'TemplateDetail_TextArea_Description']</value>
      <webElementGuid>261bda8b-5df2-4802-aae1-a5558f3821b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
