<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Run_b18-TextArea_Json</name>
   <tag></tag>
   <elementGuidId>6d3098c5-f7c2-4a78-a343-f7b819b22108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b18-TextArea_Json']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b18-TextArea_Json</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter Json&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a27012ee-5dca-47b1-81b9-26ab035377cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control resizable-textarea OSFillParent</value>
      <webElementGuid>174395a2-9ad7-4384-a769-56f9b0838ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>8d74b810-3937-4491-a782-bcd994f6b8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Json</value>
      <webElementGuid>e338ca04-5526-4da6-98c4-bc8284ffbd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b18-TextArea_Json</value>
      <webElementGuid>cc03532c-297e-492a-bb35-86be78cb4776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f8714b0-6ef1-41b9-8031-d46426bed822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b18-TextArea_Json&quot;)</value>
      <webElementGuid>2551fb35-a469-4a11-8ad6-2657918579fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b18-TextArea_Json']</value>
      <webElementGuid>5b6320be-d6e2-47a2-b6e7-f8c9ea266087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b18-b17-Content']/div/div/div[2]/span/textarea</value>
      <webElementGuid>77e93484-06e9-4077-a9ae-62e7df53c458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/textarea</value>
      <webElementGuid>78bb60bc-6616-4d84-971c-36c6318356b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Enter Json' and @id = 'b18-TextArea_Json']</value>
      <webElementGuid>bc15ad16-7e23-4afc-b5e4-75357fec44c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
