<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SN001_ScriptTemplate_Validation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>munya@equatorbi.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ffca7aa6-91a5-4836-a060-2cdcd5933f1c</testSuiteGuid>
   <testCaseLink>
      <guid>b453c4f1-16cf-4732-9d4e-75d46dc8c339</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01 - Add Script Template</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>70ebb48a-ae62-40cb-b66e-fc6bbcf30ea2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ScriptTemplateManager/Credentials</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67ab5067-f82c-4efd-8d00-a7a8f2bc78e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ce8ef7c-4788-4b24-a774-03eefadab7f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>941f564c-5715-44a8-b15f-df13cfebc723</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4e5598f-76d1-49a2-9ea9-1f8e4b4cd3e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53df918b-884f-4973-86c6-f1f2c9d7b61b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8a5b563-4bca-4c4d-8db1-cce8c72aac20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2097ce6c-6701-46df-894e-d190c306bab2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
